"""
Prelude module for REPL environment.

This module imports all standard library modules that should be available
in the REPL namespace. Imports must be at the top level (not exec'd) to
satisfy componentize-py's build-time dependency resolution requirement.

See: https://github.com/bytecodealliance/componentize-py?tab=readme-ov-file#known-limitations

## Auto-generated

This file is AUTO-GENERATED by generate_prelude.py. Do not edit manually!
To regenerate: uv run generate_prelude.py
"""

# ruff: noqa: F401, I001
# fmt: off

# ============================================================================
# Nested/Lazy Dependencies (Non-Top-Level Imports)
# These imports are NOT at module top-level - they're inside functions,
# classes, or conditionals. Must be explicit for componentize-py.
# ============================================================================

import _abc  # Found in abc: nested in try/except
import _asyncio  # C extension or immediate dependency of asyncio
import _bisect  # C extension or immediate dependency of random
import _blake2  # Found in hashlib: nested in function __get_builtin_constructor -> try/except -> conditional -> conditional -> conditional -> conditional -> conditional
import _collections  # Found in collections: nested in try/except
import _collections_abc  # Found in types: nested in function coroutine
import _contextvars  # C extension or immediate dependency of asyncio
import _csv  # C extension or immediate dependency of csv
import _datetime  # Found in datetime: nested in try/except
import _decimal  # Found in decimal: nested in try/except
import _functools  # Found in functools: nested in try/except
import _heapq  # C extension or immediate dependency of asyncio
import _json  # C extension or immediate dependency of json
import _md5  # Found in hashlib: nested in function __get_builtin_constructor -> try/except -> conditional -> conditional
import _opcode  # C extension or immediate dependency of asyncio
import _py_abc  # Found in abc: nested in try/except
import _pydatetime  # Found in datetime: nested in try/except
import _random  # C extension or immediate dependency of random
import _sha1  # Found in hashlib: nested in function __get_builtin_constructor -> try/except -> conditional
import _sha2  # Found in hashlib: nested in function __get_builtin_constructor -> try/except -> conditional -> conditional -> conditional -> conditional
import _sha3  # Found in hashlib: nested in function __get_builtin_constructor -> try/except -> conditional -> conditional -> conditional -> conditional -> conditional -> conditional -> conditional
import _statistics  # C extension or immediate dependency of statistics
import _string  # C extension or immediate dependency of asyncio
import _strptime  # Found in _pydatetime: nested in class datetime -> function strptime
import _struct  # C extension or immediate dependency of asyncio
import _tokenize  # C extension or immediate dependency of asyncio
import _typing  # C extension or immediate dependency of asyncio
import _weakrefset  # C extension or immediate dependency of asyncio
import ast  # Found in traceback: nested in function _extract_caret_anchors_from_line_segment
import copy  # Found in collections: nested in class UserDict -> function copy
import heapq  # Found in collections: nested in class Counter -> function most_common
import locale  # Found in _pydecimal: nested in try/except
import logging  # Found in hashlib: nested in try/except
import warnings  # Found in enum: nested in class Enum -> function _generate_next_value_ -> try/except
import weakref  # Found in functools: nested in function singledispatch

# ============================================================================
# Main Stdlib Modules
# These are the modules available in the REPL namespace
# ============================================================================

import abc
import asyncio
import base64
import collections
import csv
import dataclasses
import datetime
import decimal
import difflib
import enum
import fractions
import functools
import hashlib
import inspect
import itertools
import json
import math
import os
import pprint
import random
import re
import secrets
import statistics
import string
import sys
import textwrap
import time
import traceback
import typeguard
import types
import typing
import typing_extensions

# Reference desired modules
__modules__ = [
    abc,
    asyncio,
    base64,
    collections,
    csv,
    dataclasses,
    datetime,
    decimal,
    difflib,
    enum,
    fractions,
    functools,
    hashlib,
    inspect,
    itertools,
    json,
    math,
    os,
    pprint,
    random,
    re,
    secrets,
    statistics,
    string,
    sys,
    textwrap,
    time,
    traceback,
    typeguard,
    types,
    typing,
    typing_extensions,
]

# Export all imported modules
__all__ = [
    '__modules__',
    '_abc',
    '_asyncio',
    '_bisect',
    '_blake2',
    '_collections',
    '_collections_abc',
    '_contextvars',
    '_csv',
    '_datetime',
    '_decimal',
    '_functools',
    '_heapq',
    '_json',
    '_md5',
    '_opcode',
    '_py_abc',
    '_pydatetime',
    '_random',
    '_sha1',
    '_sha2',
    '_sha3',
    '_statistics',
    '_string',
    '_strptime',
    '_struct',
    '_tokenize',
    '_typing',
    '_weakrefset',
    'ast',
    'copy',
    'heapq',
    'locale',
    'logging',
    'warnings',
    'weakref',
    'abc',
    'asyncio',
    'base64',
    'collections',
    'csv',
    'dataclasses',
    'datetime',
    'decimal',
    'difflib',
    'enum',
    'fractions',
    'functools',
    'hashlib',
    'inspect',
    'itertools',
    'json',
    'math',
    'os',
    'pprint',
    'random',
    're',
    'secrets',
    'statistics',
    'string',
    'sys',
    'textwrap',
    'time',
    'traceback',
    'typeguard',
    'types',
    'typing',
    'typing_extensions',
]
